### ISSUE TITLE
Implement collision resolution

### ISSUE THREAD

**Issue by knyazer** [DelftMercurians/cotix#16]
Implement collision resolution for two arbitrary ```Body```s, given the point of collision:
- [x] Resolve collision ignoring the angular momentum.
- [x] Resolve collision with angular momentum.
- [x] Add friction effect during the collision

**Comment by mikhail-vlasenko** [comment]
could you please point me to a resource that describes what you want to be implemented? do I do Expanding Polytope Algorithm? or are there some more preferable methods? does this follow what you want? https://dyn4j.org/2010/05/epa-expanding-polytope-algorithm/

**Comment by knyazer** [comment]
we have implementation of EPA already
the last commit on the main

**Comment by knyazer** [comment]
But, besides, I want you to implement only the physics part
So, effectively you have two AbstractBodies, and you already given a point of the collision, and you want to change the positions/velocities so that they are 'correct'

**Comment by knyazer** [comment]
You can look into my implementation of EPA, that was quite painful to write, and maybe you could improve it? Besides, we don't really need exact penetration depth usually, so we are good to go with some rough approximations, and there are some algorithms that can compute them, but I started with EPA since it would allow us to have sort of better multipenetration resolution (hopefully). 

BTW, for the future, I have an idea how using EPA we can get an approximation of the penetration depth, that would be useful. We can store the penetration depth, and apply it smoothly throughout few iterations, while making random EPA recomputations: this would lead to a decent performance boost i guess

**Comment by knyazer** [comment]
Also, don't implement a ```Body``` class yet, I am going to finish it up today/tomorrow.

**Comment by knyazer** [comment]
I would appreciate if you could take a look at the EPA implementation, maybe you can fix some TODOs? Also, using buffers for checkpointed while loop is a nice idea, but I was not able to get a decent performance with them

**Comment by knyazer** [comment]
EPA implementation is the function ```_get_closest_minkowski_diff```

**Comment by mikhail-vlasenko** [comment]
thanks, tbh i dont feel too confident about jax and collision resolution algorithms but I'll see what I can do

**Comment by knyazer** [comment]
> thanks, tbh i dont feel too confident about jax and collision resolution algorithms yet, but I'll see what I can do

Yeah, that was actually the reason why I wrote the EPA myself, since, as you can probably see, the code is extremely hard to understand, and it is hard to understand why I took one or another decision. Probably you could try to focus on the physics part, though, since we don't have final implementations of the ```Body's``` it might be problematic. But most of the logic should remain the same, so does not really matter that much. But you won't be able to write tests until I finish the ```Body``` implementation
